### PR TITLE
Fix for issue 176

### PR DESCRIPTION
**Pull request by rrahimm**
https://wwwin-github.cisco.com/netascode/nac-sdwan/issues/176

### CODE REVIEW

**Comment by rrahimm** [comment]
Hello @danischm 

Kindly review and approve.

**Comment by vjoshevs** [comment]
Fix bug with loss_threshold_percentage under traffic data.

**Comment by rrahimm** [comment]
Hello @danischm 

Can you review and approve

**Review by tzarski0 — APPROVED** [review]
approved

**Pull request merged**
